# Generated by Django 4.2 on 2023-05-18 12:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0003_storystructure_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiillustrationprompt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aiillustrationprompt',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PromptRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='prompt_images/')),
                ('illustration_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prompts.aiillustrationprompt')),
            ],
        ),
    ]
