# Generated by Django 4.2 on 2023-05-20 18:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0004_aiillustrationprompt_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storystructure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storystructure',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='promptrecord',
            name='illustration_prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_record', to='prompts.aiillustrationprompt'),
        ),
    ]
