# Generated by Django 4.2 on 2023-05-28 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0005_storystructure_created_at_storystructure_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiillustrationprompt',
            name='leading_question',
        ),
    ]
