# Generated by Django 4.2 on 2023-05-28 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0006_remove_aiillustrationprompt_leading_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiillustrationprompt',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prompts.storystructure'),
        ),
    ]
