# Generated by Django 4.2 on 2024-01-21 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0007_aiillustrationprompt_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promptrecord',
            name='email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
